MockBlogBundle\Entity\MockblogCategory:
    type: entity
    table: mockblog_category
    indexes:
        slug:
            columns:
                - slug
        name:
            columns:
                - name
        parent:
            columns:
                - parent_id
    id:
        id:
          type: integer
          generator:
            strategy: AUTO
    fields:
        created:
            type: datetime
            nullable: false
            comment: ''
        name:
            type: string
            nullable: false
            length: 50
            fixed: false
            comment: ''
        description:
            type: text
            nullable: false
            length: null
            fixed: false
            comment: ''
#        parentId:
#            type: integer
#            nullable: true
#            unsigned: false
#            comment: ''
#            default: '0'
#            column: parent_id
        slug:
            type: string
            nullable: false
            length: 150
            fixed: false
            comment: ''
        picture:
            type: string
            nullable: true
            length: 150
            fixed: false
            comment: ''
        totalPost:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: total_post
    oneToMany:
        children:
            targetEntity: MockblogCategory
            mappedBy: parent
    manyToOne:
        parent:
            name: parent_id
            targetEntity: MockblogCategory
            cascade: {  }
            inversedBy: children
    lifecycleCallbacks: {  }
