MockBlogBundle\Entity\MockblogTag:
    type: entity
    table: mockblog_tag
    indexes:
        user_id:
            columns:
                - user_id
        name:
            columns:
                - name
    uniqueConstraints:
        slug:
            columns:
                - slug
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        created:
            type: datetime
            nullable: false
            comment: ''
        name:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        totalPost:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            default: '0'
            column: total_post
    manyToOne:
        user:
            targetEntity: User
            cascade: { }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
